#!/usr/bin/env bash
# Niko studio — one-shot VPS installer.
#
# Usage (on a fresh Ubuntu/Debian VPS, as root):
#
#   curl -fsSL https://raw.githubusercontent.com/<you>/niko/main/install.sh \
#     | bash -s -- studio.example.com you@example.com
#
# Arguments:
#   $1  DOMAIN      — DNS name pointing at this VPS (A/AAAA record already set)
#   $2  EMAIL       — email used by Let's Encrypt (optional, defaults to admin@DOMAIN)
#
# The script is idempotent: re-running it only applies missing pieces.

set -euo pipefail

DOMAIN="${1:-}"
EMAIL="${2:-}"
REPO="${NIKO_REPO:-https://github.com/teh0/niko.git}"
TARGET="${NIKO_TARGET:-/opt/niko}"
BRANCH="${NIKO_BRANCH:-main}"

bold() { printf "\033[1m%s\033[0m\n" "$*"; }
info() { printf "\033[36m▶\033[0m %s\n" "$*"; }
warn() { printf "\033[33m!\033[0m %s\n" "$*"; }
die()  { printf "\033[31m✘ %s\033[0m\n" "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "Run as root (or via sudo)."
[[ -n "$DOMAIN" ]] || die "Usage: install.sh <DOMAIN> [EMAIL]"
[[ -z "$EMAIL" ]] && EMAIL="admin@${DOMAIN}"

bold "═══ Niko studio installer ═══"
info "Domain:  $DOMAIN"
info "Email:   $EMAIL"
info "Target:  $TARGET"

# ─── 1. System deps ─────────────────────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
  info "Installing Docker…"
  curl -fsSL https://get.docker.com | sh
  systemctl enable --now docker
else
  info "Docker already present ($(docker --version | cut -d, -f1))."
fi

if ! docker compose version >/dev/null 2>&1; then
  die "Docker Compose plugin missing — reinstall Docker via get.docker.com."
fi

for pkg in git make openssl ca-certificates ufw; do
  command -v "$pkg" >/dev/null 2>&1 || apt-get install -y "$pkg" || true
done

# ─── 2. Firewall ───────────────────────────────────────────────────────
if command -v ufw >/dev/null 2>&1; then
  info "Opening ports 22, 80, 443 in ufw…"
  ufw allow OpenSSH >/dev/null || true
  ufw allow 80/tcp  >/dev/null || true
  ufw allow 443/tcp >/dev/null || true
  ufw --force enable >/dev/null || true
fi

# ─── 3. Clone or update repo ───────────────────────────────────────────
if [[ -d "$TARGET/.git" ]]; then
  info "Updating existing checkout at $TARGET…"
  git -C "$TARGET" fetch origin "$BRANCH"
  git -C "$TARGET" checkout "$BRANCH"
  git -C "$TARGET" reset --hard "origin/$BRANCH"
else
  info "Cloning $REPO into $TARGET…"
  mkdir -p "$(dirname "$TARGET")"
  git clone --branch "$BRANCH" "$REPO" "$TARGET"
fi

cd "$TARGET"

# ─── 4. Generate .env if missing ───────────────────────────────────────
if [[ ! -f .env ]]; then
  info "Generating .env (first-time install)…"
  POSTGRES_PASSWORD="$(openssl rand -hex 24)"
  WEBHOOK_SECRET="$(openssl rand -hex 24)"

  cat > .env <<EOF
# Auto-generated by install.sh on $(date -u +%FT%TZ)
DATABASE_URL=postgresql://niko:${POSTGRES_PASSWORD}@postgres:5432/niko?schema=public
REDIS_URL=redis://redis:6379

DOMAIN=${DOMAIN}
CADDY_EMAIL=${EMAIL}
PUBLIC_URL=https://${DOMAIN}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# Fill these in before using the studio:
GITHUB_APP_ID=
GITHUB_APP_PRIVATE_KEY=
GITHUB_APP_CLIENT_ID=
GITHUB_APP_CLIENT_SECRET=
GITHUB_WEBHOOK_SECRET=${WEBHOOK_SECRET}
GITHUB_PAT=

# Optional:
FIGMA_API_KEY=
ANTHROPIC_API_KEY=

MAX_CONCURRENT_AGENTS=4
RATE_LIMIT_PAUSE_MINUTES=60
WORKSPACE_DIR=/workspaces
EOF
  chmod 600 .env
  warn "Generated .env with random secrets. Edit it to add GitHub App credentials."
else
  info ".env already present — keeping it. Edit manually if needed."
fi

# ─── 5. Build + start ──────────────────────────────────────────────────
info "Building images (first build can take ~3-5 min)…"
docker compose build

info "Starting services…"
docker compose up -d

info "Running database migrations…"
docker compose exec -T web sh -c 'pnpm db:deploy' || warn "Migration failed — run 'make migrate' manually once .env is filled."

# ─── 6. Final instructions ─────────────────────────────────────────────
bold "═══ Next steps ═══"
cat <<EOF

1. Edit $TARGET/.env and fill in:
     - GITHUB_APP_ID, GITHUB_APP_PRIVATE_KEY, GITHUB_APP_CLIENT_ID,
       GITHUB_APP_CLIENT_SECRET  (create at https://github.com/settings/apps/new)
     - FIGMA_API_KEY  (optional, enables Figma MCP)

   The webhook URL you give GitHub is:
     https://${DOMAIN}/api/webhooks/github
   The webhook secret is already in .env as GITHUB_WEBHOOK_SECRET.

2. Authenticate Claude MAX on this VPS (one-time, interactive):
     cd $TARGET && make login

3. Restart to pick up your .env edits:
     cd $TARGET && make restart

4. Verify:
     curl https://${DOMAIN}/api/health
     open https://${DOMAIN}

Dashboard URL:  https://${DOMAIN}
Webhook URL:    https://${DOMAIN}/api/webhooks/github
Logs:           cd $TARGET && make logs
EOF
