#!/usr/bin/env bash
# Local dev bootstrap for Niko. Idempotent — re-run any time.
#
# What it does:
#   1. Check Node + pnpm are installed.
#   2. `pnpm install` if node_modules is missing.
#   3. Start Postgres + Redis via docker-compose.dev.yml.
#   4. Wait for Postgres to accept connections.
#   5. Create .env if missing (with random secrets, local URLs).
#   6. Generate Prisma client + run migrations (creates DB schema).
#   7. Check `claude` CLI auth status.
#   8. Print the remaining manual steps (GitHub App setup).

set -euo pipefail

cd "$(dirname "$0")/.."

bold() { printf "\033[1m%s\033[0m\n" "$*"; }
info() { printf "\033[36m▶\033[0m %s\n" "$*"; }
ok()   { printf "\033[32m✔\033[0m %s\n" "$*"; }
warn() { printf "\033[33m!\033[0m %s\n" "$*"; }
die()  { printf "\033[31m✘ %s\033[0m\n" "$*" >&2; exit 1; }

bold "═══ Niko local bootstrap ═══"

# ─── 1. Tooling ─────────────────────────────────────────────────────────
command -v node >/dev/null 2>&1 || die "Node.js not found. Install Node 22+."
command -v pnpm >/dev/null 2>&1 || die "pnpm not found. Try: corepack enable && corepack prepare pnpm@10 --activate"
command -v docker >/dev/null 2>&1 || die "Docker not found. Install Docker Desktop (macOS) or Docker Engine (Linux)."

NODE_MAJOR="$(node -v | sed 's/v\([0-9]*\).*/\1/')"
if (( NODE_MAJOR < 22 )); then
  warn "Node $NODE_MAJOR detected — Niko targets Node 22+. Things may work but aren't tested on older."
fi

ok "Tooling present."

# ─── 2. Dependencies ────────────────────────────────────────────────────
if [[ ! -d node_modules ]]; then
  info "Installing dependencies (pnpm install)…"
  pnpm install
else
  info "node_modules present — skipping pnpm install (run 'pnpm install' manually if you updated package.json)."
fi
ok "Dependencies ready."

# ─── 3. Postgres + Redis ────────────────────────────────────────────────
info "Starting Postgres + Redis containers…"
docker compose -f docker-compose.dev.yml up -d >/dev/null

info "Waiting for Postgres to accept connections…"
ATTEMPTS=0
until docker compose -f docker-compose.dev.yml exec -T postgres pg_isready -U niko >/dev/null 2>&1; do
  ATTEMPTS=$((ATTEMPTS + 1))
  if (( ATTEMPTS > 30 )); then
    die "Postgres didn't come up after 30s. Check 'docker compose -f docker-compose.dev.yml logs postgres'."
  fi
  sleep 1
done
ok "Postgres ready on :5432."
ok "Redis ready on :6379."

# ─── 4. .env ────────────────────────────────────────────────────────────
if [[ ! -f .env ]]; then
  info "No .env found — generating one with random secrets."
  WEBHOOK_SECRET="$(openssl rand -hex 24 2>/dev/null || node -e 'console.log(require("crypto").randomBytes(24).toString("hex"))')"

  cat > .env <<EOF
# Generated by scripts/bootstrap.sh on $(date -u +%FT%TZ)
DATABASE_URL=postgresql://niko:niko@localhost:5432/niko?schema=public
REDIS_URL=redis://localhost:6379

PUBLIC_URL=http://localhost:3000
WORKSPACE_DIR=/tmp/niko-workspaces

# Fill these in after you create your GitHub App — see README.
GITHUB_APP_ID=
GITHUB_APP_PRIVATE_KEY=
GITHUB_APP_CLIENT_ID=
GITHUB_APP_CLIENT_SECRET=
GITHUB_WEBHOOK_SECRET=${WEBHOOK_SECRET}
# Or the PAT fallback (simpler for first local test):
GITHUB_PAT=

# Optional:
FIGMA_API_KEY=
ANTHROPIC_API_KEY=

MAX_CONCURRENT_AGENTS=4
RATE_LIMIT_PAUSE_MINUTES=60
EOF
  ok "Wrote .env (chmod 600)."
  chmod 600 .env
else
  info ".env already present — keeping it."
fi

# ─── 5. Prisma ──────────────────────────────────────────────────────────
info "Generating Prisma client…"
pnpm db:generate >/dev/null 2>&1 || pnpm db:generate

info "Running migrations…"
# --name init on first run; noop afterwards.
if pnpm exec prisma migrate status --schema=prisma/schema.prisma 2>&1 | grep -q "No migration found"; then
  pnpm exec prisma migrate dev --name init --skip-seed
else
  pnpm exec prisma migrate dev --skip-seed --name "auto-$(date +%s)" 2>&1 | tail -5 || true
fi
ok "Schema applied."

# ─── 6. Claude MAX auth ─────────────────────────────────────────────────
if command -v claude >/dev/null 2>&1; then
  if claude /status 2>&1 | grep -qi 'api key'; then
    warn "Claude CLI is using an API key, not the MAX OAuth session."
    warn "For the Niko studio, prefer: 'claude logout && claude login' to switch to MAX."
  elif claude /status >/dev/null 2>&1; then
    ok "Claude CLI authenticated."
  else
    warn "Claude CLI installed but not logged in. Run: claude login"
  fi
else
  warn "Claude CLI not found. Install:  npm install -g @anthropic-ai/claude-code"
  warn "Then: claude login"
fi

# ─── 7. Next steps ──────────────────────────────────────────────────────
bold "═══ Bootstrap done. Next steps ═══"
cat <<'EOF'

1. Create a GitHub App (one-time) — https://github.com/settings/apps/new
   Permissions: Contents (R/W), Pull requests (R/W), Metadata (R).
   Events: Pull request, Pull request review, Push.
   Homepage URL: http://localhost:3000
   Webhook URL:  leave blank for now (we'll test without webhooks; dashboard
                 has a manual "Approve gate" button)
   Generate a private key, copy the .pem file path.

   Then convert the PEM to a one-liner for .env:
     make encode-pem FILE=path/to/your-key.pem
   Paste the output into GITHUB_APP_PRIVATE_KEY in .env.

   Also fill: GITHUB_APP_ID, GITHUB_APP_CLIENT_ID, GITHUB_APP_CLIENT_SECRET.

   Install the App on one of your GitHub accounts, then install it on a
   test repo (e.g. create a fresh empty repo). Note the Installation ID
   from the install URL — you'll paste it when creating a project.

   Shortcut: if you don't want to set up a GitHub App right now, put a
   fine-grained Personal Access Token in GITHUB_PAT instead (Contents R/W,
   Pull requests R/W on your test repo). No webhooks, fully manual gates.

2. Start the studio in two terminals:
     Terminal A:   pnpm dev
     Terminal B:   pnpm worker

3. Open http://localhost:3000 → + New → chat with the Intake agent →
   create the project → watch agents go on your test repo.

Approving gates locally: open the project in the dashboard and click
"Approve" on pending gates (or review/approve the PR directly on GitHub;
without a webhook, the dashboard button is the reliable path).

EOF
