#!/usr/bin/env bash
# Zero-setup local test. Everything runs in Docker — you only need Docker
# and (one-time) `gh` + `claude login` inside the container.
#
# make up  →  ./scripts/up.sh

set -euo pipefail
cd "$(dirname "$0")/.."

bold() { printf "\033[1m%s\033[0m\n" "$*"; }
info() { printf "\033[36m▶\033[0m %s\n" "$*"; }
ok()   { printf "\033[32m✔\033[0m %s\n" "$*"; }
warn() { printf "\033[33m!\033[0m %s\n" "$*"; }
die()  { printf "\033[31m✘ %s\033[0m\n" "$*" >&2; exit 1; }

command -v docker >/dev/null 2>&1 || die "Docker not installed. Install Docker Desktop."

bold "═══ Niko — Docker local test ═══"

COMPOSE="docker compose -f docker-compose.yml -f docker-compose.local.yml"

# ─── 1. .env (random secrets for local) ─────────────────────────────────
if [[ ! -f .env ]]; then
  info "No .env found — generating with random secrets…"
  PG_PW="$(openssl rand -hex 16 2>/dev/null || node -e 'console.log(require("crypto").randomBytes(16).toString("hex"))')"
  WH="$(openssl rand -hex 24 2>/dev/null || node -e 'console.log(require("crypto").randomBytes(24).toString("hex"))')"
  # Find a free port starting from 3000.
  PORT=3000
  while lsof -nP -iTCP:$PORT -sTCP:LISTEN >/dev/null 2>&1; do
    PORT=$((PORT + 1))
  done
  [[ "$PORT" != "3000" ]] && warn "Port 3000 is taken — using $PORT instead."

  cat > .env <<EOF
# Auto-generated by scripts/up.sh on $(date -u +%FT%TZ)
POSTGRES_PASSWORD=${PG_PW}
NIKO_WEB_PORT=${PORT}
PUBLIC_URL=http://localhost:${PORT}
GITHUB_WEBHOOK_SECRET=${WH}
GITHUB_PAT=
GITHUB_APP_ID=
GITHUB_APP_PRIVATE_KEY=
GITHUB_APP_CLIENT_ID=
GITHUB_APP_CLIENT_SECRET=
FIGMA_API_KEY=
ANTHROPIC_API_KEY=
MAX_CONCURRENT_AGENTS=4
RATE_LIMIT_PAUSE_MINUTES=60
EOF
  chmod 600 .env
  ok "Wrote .env."
fi

# ─── 2. Inject gh token if GITHUB_PAT is empty and gh is available ──────
CUR_PAT="$(grep -E '^GITHUB_PAT=' .env 2>/dev/null | sed -E 's/^GITHUB_PAT="?([^"]*)"?$/\1/' || true)"
CUR_APP_ID="$(grep -E '^GITHUB_APP_ID=' .env 2>/dev/null | sed -E 's/^GITHUB_APP_ID="?([^"]*)"?$/\1/' || true)"
if [[ -z "${CUR_PAT:-}" && -z "${CUR_APP_ID:-}" ]]; then
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    info "Injecting your gh token as GITHUB_PAT (no GitHub App needed for local test)…"
    ./scripts/set-env.sh GITHUB_PAT "$(gh auth token)"
    ok "GITHUB_PAT set."
  else
    warn "No GitHub credentials in .env and gh CLI not logged in."
    warn "Either run 'gh auth login' then re-run 'make up', or paste a PAT into GITHUB_PAT in .env."
  fi
fi

# ─── 3. Build + start ───────────────────────────────────────────────────
info "Building images (first build takes ~2-3 min, then cached)…"
$COMPOSE build >/dev/null

info "Starting services (postgres, redis, web, worker)…"
$COMPOSE up -d

PORT="$(grep -E '^NIKO_WEB_PORT=' .env 2>/dev/null | sed -E 's/^NIKO_WEB_PORT="?([^"]*)"?$/\1/' || echo 3000)"
: "${PORT:=3000}"

info "Waiting for web to be healthy on :${PORT}…"
ATTEMPTS=0
until curl -fs http://localhost:${PORT}/api/health >/dev/null 2>&1; do
  ATTEMPTS=$((ATTEMPTS + 1))
  if (( ATTEMPTS > 60 )); then
    warn "Web didn't come up after 60s. Tail logs with: make logs"
    break
  fi
  sleep 1
done

# ─── 4. Claude MAX login (inside worker container, one-time) ────────────
CLAUDE_OK=0
if $COMPOSE exec -T worker claude /status >/dev/null 2>&1; then
  CLAUDE_OK=1
fi

bold ""
bold "═══ Niko is up ═══"
echo ""
echo "  Dashboard:    http://localhost:${PORT}"
echo "  Health:       http://localhost:${PORT}/api/health"
echo "  Logs:         make logs"
echo "  Stop:         make down"
echo ""

if [[ "$CLAUDE_OK" = "1" ]]; then
  ok "Claude CLI already authenticated inside the worker container."
else
  bold "ONE remaining step — authenticate Claude MAX inside the worker container:"
  echo ""
  echo "    make login"
  echo ""
  echo "  (Opens a URL in your browser, you paste the code back — 10 seconds)"
fi

echo ""
echo "Then open http://localhost:3000 and click + New."
